spec:
  template:
    spec:
      volumes:
        - name: app-map
          configMap:
            name: keycloak-config
      containers:
        - name: keycloak
          volumeMounts:
            - name: app-map
              mountPath: /tmp/kogito-realm.json
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: keycloak.admin.user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: keycloak.admin.password
            - name: KEYCLOAK_IMPORT_NOTDONE
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: keycloak.realm.json
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: keycloak.db.vendor