spec:
  template:
    spec:
      containers:
        - name: kogito-travel-agency-visas-jvm
          env:
            - name: KOGITO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: kogito-app-configs
                  key: kogito.service.url.visas
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: kafka.bootstrap.servers
            - name: KOGITO_DATAINDEX_HTTP_URL
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: kogito.dataindex.httpurl
            - name: KOGITO_DATAINDEX_WS_URL
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: kogito.dataindex.wsurl
            - name: QUARKUS_INFINISPAN_CLIENT_SERVER_LIST
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: quarkus.infinispan.client.serverlist
            - name: QUARKUS_INFINISPAN_CLIENT_USE_AUTH
              value: 'true'
            - name: QUARKUS_INFINISPAN_CLIENT_AUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: quarkus.infinispan.client.authusername
            - name: QUARKUS_INFINISPAN_CLIENT_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infinispan-generated-secret
                  key: password
          ports:
            - containerPort: 8090
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 64Mi